/**
 * Enrich the Landkarte graph further.
 *
 * Reads the build-kg output (data/graph/landscape.ttl) and writes
 * data/graph/d-stack-kg.ttl.
 *
 * The enrichment itself is postponed.
 * It is produced now anyway so the use cases can already build on it.
 *
 * Run: npm run 2-enrich
 */

import { storeFromTurtles, storeToTurtle } from "@foerderfunke/sem-ops-utils"
import { ROOT, GRAPH, PREFIXES } from "../common/utils.js"
import path from "path"
import fs from "fs"

const IN = path.join(GRAPH, "landscape.ttl")
const OUT = path.join(GRAPH, "d-stack-kg.ttl")

if (!fs.existsSync(IN)) throw new Error(`missing ${path.relative(ROOT, IN)} — run the build-kg phase first (npm run 1-build-kg)`)

const graph = storeFromTurtles([fs.readFileSync(IN, "utf8")])

// TODO

fs.mkdirSync(GRAPH, { recursive: true })
fs.writeFileSync(OUT,
    "# The Deutschland-Stack knowledge graph. Generated by the enrich phase\n" +
    "# (npm run 2-enrich) from data/graph/landscape.ttl — not hand-edited.\n" +
    await storeToTurtle(graph, PREFIXES))
console.log(`OK: ${graph.size} triples -> data/graph/d-stack-kg.ttl`)
