/**
 * Enrich phase — produces the technical knowledge graph.
 *
 * Reads the build-kg output (data/1-build-kg/landscape.ttl) and writes
 * data/2-enrich-kg/d-stack-kg.ttl, adding enrichment below.
 *
 * The administrative layer is kept in separate committed files, loaded alongside
 * this one by whatever needs the join:
 *   - pvog-leistungen.ttl       real services, ingested from PVOG (npm run pvog:fetch)
 *   - fim-leistungen.ttl        FIM Leistungs-Steckbriefe + a central FIM Datenschema (npm run fim:fetch)
 *   - fit-connect.ttl           FIT-Connect Zustellpunkte + the Fachdatenschemata they collect (npm run fit-connect:fetch)
 *   - pvog-dstack-bridge.assumed.ttl     hand-curated links: which real Landkarte elements an
 *                                        Onlinedienst is built on (a proposal, not derived)
 *
 * Run: npm run kg:enrich
 */

import { storeFromTurtles, sparqlSelect, addTurtleToStore, storeToTurtle } from "@foerderfunke/sem-ops-utils"
import { ROOT, UPSTREAM, LANDSCAPE_TTL, DSTACK_TTL, PREFIXES } from "../common/utils.js"
import path from "path"
import fs from "fs"

if (!fs.existsSync(LANDSCAPE_TTL)) throw new Error(`missing ${path.relative(ROOT, LANDSCAPE_TTL)} — run the build-kg phase first (npm run kg:build)`)

const graph = storeFromTurtles([fs.readFileSync(LANDSCAPE_TTL, "utf8")])

// Carry the landscape2 item id (the deep-link slug) onto each StackElement. landscape2
// derives it from the category/subcategory/name with quirks we don't want to re-invent
// (it drops non-ASCII letters, keeps '+', leaves stray separators), so we take the
// authoritative value straight from the published full.json — joined by name (a clean
// 1:1 match) — rather than reconstruct it. It lets consumers (the webapp) link a tile
// back to its popup at technologie.deutschland-stack.gov.de/?item=<id>.
//
// Why here and not in the build phase: the id is a landscape2-*generated* value that lives
// only in full.json (its output). The build lifts the reconstructed landscape.yml (the
// landscape2 *input*), which never carries it — so this join naturally lands in this
// post-build step.
const idByName = new Map(
    JSON.parse(fs.readFileSync(path.join(UPSTREAM, "full.json"), "utf8")).items.map(it => [it.name, it.id]))
const elements = await sparqlSelect(`
    PREFIX dstack: <https://deutschland-stack.gov.de/vocab#>
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    SELECT ?el ?label WHERE {
        ?el a dstack:StackElement ;
            skos:prefLabel ?label
    }`, [graph])
const itemIdTriples = elements
    .filter(r => idByName.has(r.label))
    .map(r => `<${r.el}> dstack:landkarteItemId ${JSON.stringify(idByName.get(r.label))} .`)
addTurtleToStore(graph, `@prefix dstack: <https://deutschland-stack.gov.de/vocab#> .\n${itemIdTriples.join("\n")}`)
console.log(`enrich: +${itemIdTriples.length} dstack:landkarteItemId (of ${elements.length} StackElements)`)

fs.mkdirSync(path.dirname(DSTACK_TTL), { recursive: true })
fs.writeFileSync(DSTACK_TTL,
    "# The Deutschland-Stack technical knowledge graph. Generated by the enrich phase\n" +
    "# (npm run kg:enrich) from data/1-build-kg/landscape.ttl — not hand-edited.\n\n" +
    await storeToTurtle(graph, PREFIXES))
console.log(`OK: ${graph.size} triples -> data/2-enrich-kg/d-stack-kg.ttl`)
