/**
 * Enrich the Landkarte graph further.
 *
 * Reads the build-kg output (data/1-build-kg/landscape.ttl) and writes
 * data/2-enrich-kg/d-stack-kg.ttl.
 *
 * The enrichment itself is postponed.
 * It is produced now anyway so the use cases can already build on it.
 *
 * Run: npm run 2-enrich
 */

import { storeFromTurtles, storeToTurtle } from "@foerderfunke/sem-ops-utils"
import { ROOT, LANDSCAPE_TTL, DSTACK_TTL, PREFIXES } from "../common/utils.js"
import path from "path"
import fs from "fs"

const IN = LANDSCAPE_TTL
const OUT = DSTACK_TTL

if (!fs.existsSync(IN)) throw new Error(`missing ${path.relative(ROOT, IN)} — run the build-kg phase first (npm run 1-build-kg)`)

const graph = storeFromTurtles([fs.readFileSync(IN, "utf8")])

// TODO

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT,
    "# The Deutschland-Stack knowledge graph. Generated by the enrich phase\n" +
    "# (npm run 2-enrich) from data/1-build-kg/landscape.ttl — not hand-edited.\n" +
    await storeToTurtle(graph, PREFIXES))
console.log(`OK: ${graph.size} triples -> data/2-enrich-kg/d-stack-kg.ttl`)
